services:
  db:
    ports:
      - "3306:3306"

  django:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  prometheus:
    ports:
      - "9090:9090"

  grafana:
    ports:
      - "3000:3000"
