# Generated by Django 5.2 on 2025-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exercise_rest_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
