# Generated by Django 5.2 on 2025-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='max_reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='min_reps',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='max_reps',
        ),
        migrations.RemoveField(
            model_name='exercisetemplate',
            name='min_reps',
        ),
        migrations.AddField(
            model_name='set',
            name='max_reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='min_reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settemplate',
            name='max_reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settemplate',
            name='min_reps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
