# Generated by Django 5.2 on 2025-09-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_exercise_max_reps_remove_exercise_min_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
