# Generated by Django 5.2 on 2026-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_exercisegoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='increment_step',
            field=models.FloatField(default=2.5),
        ),
    ]
