# Generated by Django 5.2 on 2026-03-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_exercisetemplate_increment_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='increment_step',
            field=models.FloatField(default=2.5),
        ),
    ]
