# Generated by Django 5.2 on 2025-07-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_exercisetemplate_settemplate_workouttemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='date',
        ),
        migrations.AddField(
            model_name='workout',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.workouttemplate'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracker.workout'),
        ),
        migrations.AlterField(
            model_name='exercisetemplate',
            name='workout_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to='tracker.workouttemplate'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='tracker.exercise'),
        ),
        migrations.AlterField(
            model_name='settemplate',
            name='exercise_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_templates', to='tracker.exercisetemplate'),
        ),
    ]
